let
    Fonte = Web.BrowserContents("https://portais.camacari.ba.gov.br/compras/licitacoes.php"),
    #"Texto Importado" = Lines.FromText(Fonte),
    #"Convertido para Tabela" = Table.FromList(#"Texto Importado", Splitter.SplitByNothing(), null, null, ExtraValues.Error),
    #"Índice Adicionado" = Table.AddIndexColumn(#"Convertido para Tabela", "Índice", 1, 1, Int64.Type),
    #"Índice Adicionado1" = Table.AddIndexColumn(#"Índice Adicionado", "Índice.1", 0, 1, Int64.Type),
    #"Tipo Alterado" = Table.TransformColumnTypes(#"Índice Adicionado1",{{"Column1", type text}, {"Índice", type text}, {"Índice.1", type text}}),
    #"Consultas Mescladas" = Table.NestedJoin(#"Tipo Alterado", {"Índice"}, #"Tipo Alterado", {"Índice.1"}, "Tipo Alterado", JoinKind.LeftOuter),
    #"Tipo Alterado Expandido" = Table.ExpandTableColumn(#"Consultas Mescladas", "Tipo Alterado", {"Column1"}, {"Nº Licitação:"}),
    #"Coluna Duplicada" = Table.DuplicateColumn(#"Tipo Alterado Expandido", "Column1", "2ParteUrl"),
    #"Linhas Filtradas" = Table.SelectRows(#"Coluna Duplicada", each Text.Contains([Column1], "<a href=""licitacao.php?cod_licitacao")),
    #"Texto Inserido Antes do Delimitador" = Table.AddColumn(#"Linhas Filtradas", "Texto Antes do Delimitador", each Text.BeforeDelimiter([Column1], "-"), type text),
    #"Texto Aparado" = Table.TransformColumns(#"Texto Inserido Antes do Delimitador",{{"Texto Antes do Delimitador", Text.Trim, type text}}),
    #"Texto Extraído Entre os Delimitadores" = Table.TransformColumns(#"Texto Aparado", {{"Column1", each Text.BetweenDelimiters(_, ">", "<"), type text}}),
    #"Colunas Reordenadas" = Table.ReorderColumns(#"Texto Extraído Entre os Delimitadores",{"Texto Antes do Delimitador", "Column1", "Índice", "Índice.1", "Nº Licitação:"}),
    #"Texto Inserido Após o Delimitador" = Table.AddColumn(#"Colunas Reordenadas", "Modalidade", each Text.AfterDelimiter([#"Nº Licitação:"], ":", 1), type text),
    #"Texto Aparado1" = Table.TransformColumns(#"Texto Inserido Após o Delimitador",{{"Modalidade", Text.Trim, type text}}),
    #"Texto Extraído Antes do Delimitador" = Table.TransformColumns(#"Texto Aparado1", {{"Modalidade", each Text.BeforeDelimiter(_, " "), type text}}),
    #"Texto Aparado2" = Table.TransformColumns(#"Texto Extraído Antes do Delimitador",{{"Nº Licitação:", Text.Trim, type text}}),
    #"Texto Extraído Entre os Delimitadores1" = Table.TransformColumns(#"Texto Aparado2", {{"Nº Licitação:", each Text.BetweenDelimiters(_, " ", " M"), type text}}),
    #"Texto em Maiúscula" = Table.TransformColumns(#"Texto Extraído Entre os Delimitadores1",{{"Modalidade", Text.Upper, type text}}),
    #"Colunas Renomeadas" = Table.RenameColumns(#"Texto em Maiúscula",{{"Column1", "Descrição"}, {"Texto Antes do Delimitador", "Data"}}),
    #"Colunas Reordenadas1" = Table.ReorderColumns(#"Colunas Renomeadas",{"Data", "Descrição", "Índice", "Índice.1", "Nº Licitação:", "Modalidade", "2ParteUrl"}),
    #"Texto Extraído Entre os Delimitadores2" = Table.TransformColumns(#"Colunas Reordenadas1", {{"2ParteUrl", each Text.BetweenDelimiters(_, "?", """"), type text}}),
    #"Personalização Adicionada" = Table.AddColumn(#"Texto Extraído Entre os Delimitadores2", "1ParteUrl", each "https://portais.camacari.ba.gov.br/compras/licitacao.php?"),
    #"Colunas Mescladas" = Table.CombineColumns(#"Personalização Adicionada",{"1ParteUrl", "2ParteUrl"},Combiner.CombineTextByDelimiter("", QuoteStyle.None),"UrlFinal"),
    #"Função Personalizada Invocada" = Table.AddColumn(#"Colunas Mescladas", "Dados", each FunçãoDataCamaçari([UrlFinal])),
    #"Dados Expandido" = Table.ExpandTableColumn(#"Função Personalizada Invocada", "Dados", {"Comissão", "Modalidade", "Data Licitação", "Número", "Situação", "Tipo", "Horario"}, {"Comissão", "Modalidade.1", "Data Licitação", "Número", "Situação", "Tipo", "Horario"}),
    #"Erros Substituídos" = Table.ReplaceErrorValues(#"Dados Expandido", {{"Data Licitação", null}}),
    #"Erros Substituídos1" = Table.ReplaceErrorValues(#"Erros Substituídos", {{"Horario", #time(0, 0, 0)}}),
    #"Personalização Adicionada1" = Table.AddColumn(#"Erros Substituídos1", "Data de Ultima Atualização", each DateTime.LocalNow()),
    #"Changed Type" = Table.TransformColumnTypes(#"Personalização Adicionada1",{{"Data de Ultima Atualização", type datetime}, {"Data", type date}})
in
    #"Changed Type"